### PR TITLE
upgraded react-bootstrap (to 1.3.0) and fixed breaking changes

### PR DESCRIPTION
**Pull request by friedcode**

### CODE REVIEW

**Comment by jayair** [comment]
Hi there, thanks for putting this together. This is a bit of a big change for us. I'll need to change quite a lot of chapters for this. I'll look into this for our next major update.

I'll leave this open for now. So others can use it if they need.

**Comment by friedcode** [comment]
Sounds good! 👍

**Comment by jayair** [comment]
@friedcode Thanks for this! We'll be releasing this in the coming week!

**Comment by jayair** [comment]
It's alive!

https://github.com/AnomalyInnovations/serverless-stack-demo-client/releases/tag/v6.0

**Pull request merged**
